#!/usr/bin/env bash
# Install nginx web server
apt-get update
apt-get -y install nginx
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/listen 80 default_server;/a error_page 404 /404.html;' /etc/nginx/sites-available/default
service nginx restart
