#!/usr/bin/env bash
# Bash Script that uses ssh to connect using private key: ~/.ssh/holberton, user ubuntu
# My server: New 900-web-01, ubuntu, ip
# ssh -norute- ubuntu@35.229.42.147 it doesn't work 
ssh -i ~/.ssh/holberton ubuntu@35.229.42.147
